#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""
Embedder Bridge Codegen
=======================
Entry point. Parses the user's bridge WebIDL, builds the data model, then
renders Jinja2 templates into the Cargo OUT_DIR.

See bridge/models.py for the data model and bridge/templates/ for all output.
"""

from __future__ import annotations

import os
import sys

# ---------------------------------------------------------------------------
# Bootstrap paths so WebIDL parser and bridge package are importable
# ---------------------------------------------------------------------------

script_dir = os.path.dirname(os.path.abspath(__file__))
bindings_root = os.path.abspath(os.path.join(script_dir, ".."))

sys.path.insert(0, script_dir)                                          # bridge/
sys.path.insert(0, os.path.join(bindings_root, "third_party", "WebIDL"))
sys.path.insert(0, os.path.join(bindings_root, "third_party", "ply"))

from bridge.models import extract_interfaces  # noqa: E402 (after sys.path setup)


def _jinja_env(template_dir: str):
    try:
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError:
        print(
            "embedder_bridge.py: ERROR: jinja2 is not installed.\n"
            "Install it with: pip install jinja2",
            file=sys.stderr,
        )
        sys.exit(1)
    return Environment(
        loader=FileSystemLoader(template_dir),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def _parse_webidl(webidl_paths: list[str], cache_dir: str):
    import WebIDL
    os.makedirs(cache_dir, exist_ok=True)
    parser = WebIDL.Parser(cache_dir)
    for path in webidl_paths:
        if not os.path.isfile(path):
            print(f"embedder_bridge.py: WARNING: WebIDL file not found: {path}", file=sys.stderr)
            continue
        with open(path, encoding="utf-8") as f:
            parser.parse(f.read(), path)
    try:
        return parser.finish()
    except Exception as e:
        print(f"embedder_bridge.py: ERROR parsing WebIDL: {e}", file=sys.stderr)
        sys.exit(1)


def _write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _remove_stale_bridge_webidls(webidls_dir: str, current: list[str]) -> None:
    for fname in os.listdir(webidls_dir):
        if not fname.endswith(".webidl"):
            continue
        path = os.path.join(webidls_dir, fname)
        with open(path, encoding="utf-8") as f:
            first = f.readline()
        if "@generated by embedder_bridge.py" in first and fname not in current:
            os.remove(path)
    gitignore = os.path.join(webidls_dir, ".gitignore")
    with open(gitignore, "w", encoding="utf-8") as f:
        f.write("# @generated by embedder_bridge.py - do not edit by hand.\n")
        for fname in sorted(current):
            f.write(f"{fname}\n")


# ---------------------------------------------------------------------------
# Enum macro wrappers (embedder_msg / constellation_msg / script_msg)
# These three files use a different outer wrapper than the glue macros.
# ---------------------------------------------------------------------------

_ENUM_MACRO_NAMES = {
    "embedder_msg":      "define_embedder_msg",
    "constellation_msg": "define_embedder_to_constellation_message",
    "script_msg":        "define_script_thread_message",
}


def main() -> None:
    webidl_path_env = os.environ.get("SERVO_BRIDGE_WEBIDL", "")
    if not webidl_path_env:
        print(
            "error[embedder_bridge_build]: SERVO_BRIDGE_WEBIDL is not set.\n"
            "Set it to the path of your bridge WebIDL file before building.\n"
            "Example: SERVO_BRIDGE_WEBIDL=/path/to/bridge.webidl cargo build",
            file=sys.stderr,
        )
        sys.exit(1)

    out_dir = sys.argv[1]
    # webidls_dir is only passed from script_bindings/build.rs
    webidls_dir = sys.argv[2] if len(sys.argv) > 2 else None

    template_dir = os.path.join(script_dir, "bridge", "templates")
    env = _jinja_env(template_dir)

    sep = ";" if sys.platform == "win32" else ":"
    webidl_paths = [p for p in webidl_path_env.split(sep) if p]

    parser_results = _parse_webidl(webidl_paths, os.path.join(out_dir, "bridge_cache"))
    interfaces = extract_interfaces(parser_results)

    ctx_all = {"interfaces": interfaces}

    # ---- enum variant files ------------------------------------------------
    for key, macro_name in _ENUM_MACRO_NAMES.items():
        tmpl = env.get_template(f"{key}.rs.j2")
        _write(
            os.path.join(out_dir, f"embedder_bridge_{key}.rs"),
            tmpl.render(**ctx_all, macro_name=macro_name),
        )

    # ---- glue macro files --------------------------------------------------
    for name in (
        "constellation_dispatch",
        "constellation_tracing",
        "script_dispatch",
        "script_messaging",
        "servo_dispatch",
        "webview_methods",
        "webview_delegate",
    ):
        tmpl = env.get_template(f"{name}.rs.j2")
        _write(os.path.join(out_dir, f"embedder_bridge_{name}.rs"), tmpl.render(**ctx_all))

    # ---- script_bindings-only outputs (WebIDL + DOM impls) -----------------
    if webidls_dir:
        written = []
        for iface in interfaces:
            # interface WebIDL
            fname = f"{iface.name}.webidl"
            _write(
                os.path.join(webidls_dir, fname),
                env.get_template("iface.webidl.j2").render(iface=iface),
            )
            written.append(fname)

            # event WebIDL files
            for event in iface.events:
                fname = f"{event.event_iface}.webidl"
                _write(
                    os.path.join(webidls_dir, fname),
                    env.get_template("event.webidl.j2").render(event=event),
                )
                written.append(fname)

            # DOM impl .rs files
            _write(
                os.path.join(out_dir, f"bridge_{iface.name_lower}.rs"),
                env.get_template("bridge_iface.rs.j2").render(iface=iface),
            )
            for event in iface.events:
                _write(
                    os.path.join(out_dir, f"bridge_{event.event_iface_lower}.rs"),
                    env.get_template("bridge_event.rs.j2").render(event=event),
                )

        _remove_stale_bridge_webidls(webidls_dir, written)

        _write(
            os.path.join(out_dir, "bridge_window_fields.rs"),
            env.get_template("window_fields.rs.j2").render(**ctx_all),
        )
        _write(
            os.path.join(out_dir, "bridge_window_methods.rs"),
            env.get_template("window_methods.rs.j2").render(**ctx_all),
        )
        _write(os.path.join(out_dir, "bridge_window_init.rs"), "// @generated\n")
        _write(
            os.path.join(out_dir, "bridge_dom_modules.rs"),
            env.get_template("dom_modules.rs.j2").render(**ctx_all),
        )
    else:
        # Stub files so include!() calls in other crates still compile
        _write(
            os.path.join(out_dir, "bridge_window_fields.rs"),
            "// @generated\n#[derive(Default, JSTraceable, MallocSizeOf)]\npub(crate) struct BridgeWindowFields {}\n",
        )
        _write(
            os.path.join(out_dir, "bridge_window_methods.rs"),
            "// @generated\nmacro_rules! embedder_bridge_window_methods { () => {}; }\n",
        )
        _write(os.path.join(out_dir, "bridge_window_init.rs"), "// @generated\n")
        _write(os.path.join(out_dir, "bridge_dom_modules.rs"), "// @generated\n")

    n_methods = sum(len(i.methods) for i in interfaces)
    n_events  = sum(len(i.events)  for i in interfaces)
    print(
        f"embedder_bridge.py: {len(interfaces)} interface(s), "
        f"{n_methods} method(s), {n_events} event(s)."
    )


if __name__ == "__main__":
    main()
